apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  suspend: true
  backoffLimit: 3
  activeDeadlineSeconds: 82800
  ttlSecondsAfterFinished: 82800
  template:
    metadata:
      annotations:
        asset: 'xx'
    spec:
      containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
        imagePullPolicy: Always
      restartPolicy: OnFailure
      
